Use more accurate Action type w/ Dispatch type #return?
- Removed covariant markers from Action type since flow was complaining
with:

```
Error: assets/src/js/typechecking/aliases.js:18
 18: export type Dispatch = ReduxDispatch<Action>
                                          ^^^^^^ object type. Covariant property `type` incompatible with invariant use in
 15:   declare type Dispatch<A: { type: $Subtype<string> }> = DispatchAPI<A>;
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See lib: flow-typed/npm/redux_v3.x.x.js:15
```